fixtures:
  repositories:
    "wget":
      repo: "git://github.com/maestrodev/puppet-wget.git"
      ref:  "v1.5.7"
    "stdlib":
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.6.x"
  symlinks:
    sonarqube: "#{source_dir}"
